web:
  image: natali1701/nginx
  ports:
      - "8080:8080"
  links:
      - php
  volumes:
      - ./info:/usr/share/nginx/html
      - ./default-php.conf:/etc/nginx/conf.d/default.conf
php:
  image: natali1701/fpm
  ports:
      - "9000:9000"
  volumes:
      - ./info:/usr/share/nginx/html
